name: Build Android App

on:
  push:
    branches:
      - '*'  # Trigger on any branch push

jobs:
  build_apk:
    runs-on: ubuntu-latest
    container:
      image: kivy/python-for-android:latest
      options: --user root
    if: github.ref != 'refs/heads/main'
    
    steps:
    - name: Fix permissions
      run: |
        chmod -R 777 /__w
        mkdir -p /__w/_temp/_runner_file_commands
        chmod 777 /__w/_temp/_runner_file_commands
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
    
    - name: Setup Python dependencies
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir buildozer==1.5.0 "Cython<3.0"
        pip install -r requirements.txt
    
    - name: Create artifacts directory
      run: mkdir -p artifacts
    
    - name: Build APK
      run: |
        buildozer --verbose android debug 2>&1 | tee artifacts/build_apk.log
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: apk-artifacts
        path: |
          bin/*.apk
          artifacts/
        retention-days: 30

  build_aab:
    runs-on: ubuntu-latest
    container:
      image: kivy/python-for-android:latest
      options: --user root
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Fix permissions
      run: |
        chmod -R 777 /__w
        mkdir -p /__w/_temp/_runner_file_commands
        chmod 777 /__w/_temp/_runner_file_commands
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
    
    - name: Setup Python dependencies
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir buildozer==1.5.0 "Cython<3.0"
        pip install -r requirements.txt
    
    - name: Create artifacts directory
      run: mkdir -p artifacts
    
    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/keystore/ingrediguard-release-key.jks
    
    - name: Build AAB (Release)
      env:
        P4A_RELEASE_KEYSTORE: ${{ github.workspace }}/android/keystore/ingrediguard-release-key.jks
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.KEYSTORE_PASSWORD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.KEY_ALIAS_PASSWORD }}
        P4A_RELEASE_KEYALIAS: ${{ secrets.KEY_ALIAS || 'ingrediguard-release' }}
      run: |
        # Debug info to verify environment variables
        echo "Using keystore: $P4A_RELEASE_KEYSTORE"
        echo "Using key alias: $P4A_RELEASE_KEYALIAS"
        echo "Keystore exists: $([ -f $P4A_RELEASE_KEYSTORE ] && echo 'Yes' || echo 'No')"
        buildozer --verbose android release 2>&1 | tee artifacts/build_aab.log
    
    - name: Upload AAB artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: aab-artifacts
        path: |
          bin/*.aab
          artifacts/
        retention-days: 30
