name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags (v1.2.3)

# Set default permissions for all jobs
permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
    
    - name: Extract version information
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Extracted version: ${VERSION}"
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: IngrediGuard ${{ steps.extract_version.outputs.version }}
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: ${{ contains(steps.extract_version.outputs.version, '-') }}
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}

  build_release:
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add write permissions for contents
    container:
      image: kivy/python-for-android:latest
      options: --user root
    
    steps:
    - name: Fix permissions
      run: |
        chmod -R 777 /__w
        mkdir -p /__w/_temp/_runner_file_commands
        chmod 777 /__w/_temp/_runner_file_commands
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
    
    - name: Setup Python dependencies
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir buildozer==1.5.0 "Cython<3.0"
        pip install -r requirements.txt
    
    - name: Create artifacts directory
      run: mkdir -p artifacts
    
    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/keystore/ingrediguard-release-key.jks
    
    - name: Build AAB (Release)
      env:
        P4A_RELEASE_KEYSTORE: ${{ github.workspace }}/android/keystore/ingrediguard-release-key.jks
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.KEYSTORE_PASSWORD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.KEY_ALIAS_PASSWORD }}
        P4A_RELEASE_KEYALIAS: ${{ secrets.KEY_ALIAS || 'ingrediguard-release' }}
      run: |
        echo "Building release for ${{ github.ref_name }}"
        buildozer --verbose android release 2>&1 | tee artifacts/build_aab.log
    
    - name: List built files
      run: |
        echo "Checking for AAB files in bin directory:"
        ls -la bin/
        find . -name "*.aab" | xargs -I{} ls -la {}
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          bin/*.aab
        token: ${{ secrets.GITHUB_TOKEN }}
